name: Documentation Update
description: Suggest updates or additions to documentation
title: "[Docs]: "
labels: ["documentation", "improvement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Help us improve our documentation by suggesting updates or additions.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs updating?
      options:
        - README
        - API Documentation
        - Installation Guide
        - User Guide
        - Developer Guide
        - Code Comments
        - Other
    validations:
      required: true

  - type: textarea
    id: current-issue
    attributes:
      label: Current Issue
      description: What's wrong with the current documentation?
      placeholder: Describe what's missing, outdated, or unclear...
    validations:
      required: true

  - type: textarea
    id: suggested-changes
    attributes:
      label: Suggested Changes
      description: What changes would you like to see?
      placeholder: Provide detailed description of the changes...
    validations:
      required: true

  - type: input
    id: affected-sections
    attributes:
      label: Affected Sections
      description: Which sections or files need updating?
      placeholder: e.g., README.md section 3, API endpoint /users

  - type: dropdown
    id: urgency
    attributes:
      label: Urgency
      description: How urgent is this documentation update?
      options:
        - Low - Nice to have
        - Medium - Should be updated soon
        - High - Needs immediate attention
        - Critical - Blocking users
      default: 1
    validations:
      required: true

  - type: textarea
    id: additional-resources
    attributes:
      label: Additional Resources
      description: Any related links, examples, or resources?
      placeholder: Include any relevant links, examples, or references...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have checked the current documentation
          required: true
        - label: I have searched for existing documentation issues
          required: true
